name: Testing

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Testing:

    name: Node v${{ matrix.node-version }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14, 16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm test